DROP TABLE IF EXISTS users, items, bookings, requests, comments;

CREATE TABLE IF NOT EXISTS users (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     name VARCHAR(255) NOT NULL,
                                     email VARCHAR(512) NOT NULL,
                                     CONSTRAINT pk_user PRIMARY KEY (id),
                                     CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS items (
                                     id  BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                     name VARCHAR(64) NOT NULL,
                                     description VARCHAR(255) NOT NULL,
                                     is_available BOOLEAN DEFAULT FALSE,
                                     owner_id BIGINT,
                                     request_id BIGINT,
                                     CONSTRAINT fk_items_to_users FOREIGN KEY(owner_id) REFERENCES users(id),
                                     UNIQUE (id)
);

CREATE TABLE IF NOT EXISTS requests (
                                        id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                                        description VARCHAR(255) NOT NULL,
                                        requestor_id BIGINT,
                                        created TIMESTAMP WITHOUT TIME ZONE,
                                        CONSTRAINT fr_requests_to_users FOREIGN KEY (requestor_id) REFERENCES users(id),
                                        UNIQUE(id)
);

CREATE TABLE IF NOT EXISTS bookings (
                                        id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                                        start_date TIMESTAMP WITHOUT TIME ZONE,
                                        end_time TIMESTAMP WITHOUT TIME ZONE,
                                        item_id BIGINT,
                                        booker_id BIGINT,
                                        status VARCHAR(64),
                                        CONSTRAINT fk_bookings_to_items FOREIGN KEY(item_id) REFERENCES items(id),
                                        CONSTRAINT fk_bookings_to_users FOREIGN KEY(booker_id) REFERENCES users(id),
                                        UNIQUE(id)
);

CREATE TABLE IF NOT EXISTS comments (
                                        id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                                        text VARCHAR(255) NOT NULL,
                                        item_id BIGINT,
                                        author_id BIGINT,
                                        created TIMESTAMP WITHOUT TIME ZONE,
                                        CONSTRAINT fk_comments_to_items FOREIGN KEY(item_id) REFERENCES items(id),
                                        CONSTRAINT fk_comments_to_users FOREIGN KEY(author_id) REFERENCES users(id),
                                        UNIQUE(id)
);