DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS items CASCADE;
DROP TABLE IF EXISTS bookings CASCADE;
DROP TABLE IF EXISTS requests CASCADE;
DROP TABLE IF EXISTS comments CASCADE;
DROP TYPE IF EXISTS status_enum cascade;

create type status_enum as enum ('WAITING', 'APPROVED', 'REJECTED', 'CANCELED');

create table if not exists users
(
    id    bigint generated by default as identity primary key,
    email varchar(50) not null unique,
    name  varchar(50) not null
);

create table if not exists requests
(
    id           bigint generated by default as identity primary key,
    description  varchar(200),
    requestor_id bigint references users (id),
    created      timestamp with time zone
);

create table if not exists items
(
    id           bigint generated by default as identity primary key,
    name         varchar(50),
    description  varchar(200),
    is_available boolean,
    owner_id     bigint references users (id),
    request_id   bigint references requests (id)
);

create table if not exists bookings
(
    id        bigint generated by default as identity primary key,
    start_date     timestamp with time zone,
    end_time       timestamp with time zone,
    item_id   bigint references items (id),
    booker_id bigint references users (id),
    status    status_enum default 'WAITING',
    created   timestamp with time zone
);

create table if not exists comments
(
    id        bigint generated by default as identity primary key,
    text      varchar(500) not null,
    item_id   bigint references items (id),
    author_id bigint references users (id),
    created   timestamp with time zone
);
